### ISSUE TITLE
skd plugin submit issues

### ISSUE THREAD

**Issue by bowenlee** [lithiumtech/lithium-sdk#16]
My Environment:
> OS : Ubuntu 14.04.1 LTS
>nodejs : vervison v0.12.5
>Npm : version 2.11.2
>Git : version 1.9.1
>gulp: version 3.9.0
>lithium-skd : version 0.0.5 

After <code> li submit-plugin</code>

It throws following errors in console
<pre>events.js:85</br>
      throw er; // Unhandled 'error' event</br>
            ^</br>
Error: read ECONNRESET</br>
    at exports._errnoException (util.js:746:11)</br>
    at TCP.onread (net.js:559:26)</br>
</pre>

**Comment by wusiuwai** [comment]
Hi,
I found two issues. The first one is that SSL is not set up for the site you are trying to submit to. In order to submit a plugin, the site needs to have SSL enabled and set up properly. The second issue is that the plugin token is not generated. To generate the token, go to Studio->sdk and click the 'Generate Upload Token' button. Once the token is generated, use it in the 'pluginToken' of your server.conf.json.

I went ahead and enabled SSL for your site. As long as you generate and use the right plugin token, you should be able to submit a plugin.
